/** @type {import('tailwindcss').Config} */
// Palette & theme extensions taken 1:1 from the design's tailwind.config (code.html)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#c0d8e8',
        'surface-container-high': '#1a2438',
        'on-primary-fixed-variant': '#004d73',
        surface: '#0f1524',
        'on-tertiary-fixed-variant': '#4d2a73',
        'primary-fixed-dim': '#7dd3fc',
        outline: '#4a6070',
        'on-tertiary-container': '#e8d0ff',
        'on-surface-variant': '#a0b4c4',
        background: '#0a0e1a',
        'surface-container': '#141c2e',
        'secondary-container': '#1a3a4e',
        'on-tertiary': '#1a002e',
        'inverse-surface': '#e0e8f0',
        'on-primary-fixed': '#001f2e',
        'surface-container-low': '#111828',
        'primary-container': '#0e4d6e',
        'on-primary-container': '#c8eaff',
        'surface-bright': '#1a2438',
        'tertiary-fixed-dim': '#c8a0f0',
        'outline-variant': '#2a3a48',
        'primary-fixed': '#c8eaff',
        'surface-tint': '#7dd3fc',
        error: '#ff6b6b',
        'surface-container-highest': '#202c42',
        'on-error': '#1a0000',
        'error-container': '#3d1414',
        'on-secondary-fixed': '#0d1f2b',
        'on-secondary-fixed-variant': '#2a4a5e',
        'tertiary-container': '#3d2060',
        tertiary: '#c8a0f0',
        'on-tertiary-fixed': '#1a002e',
        'on-surface': '#e0e8f0',
        'tertiary-fixed': '#e8d0ff',
        'on-background': '#e0e8f0',
        'secondary-fixed': '#c0d8e8',
        'inverse-primary': '#0a4c6e',
        'inverse-on-surface': '#0a0e1a',
        'secondary-fixed-dim': '#88b4cc',
        'surface-dim': '#0f1524',
        'on-error-container': '#ffb3b3',
        'on-primary': '#001f2e',
        secondary: '#88b4cc',
        'surface-variant': '#1a2438',
        primary: '#7dd3fc',
        'surface-container-lowest': '#0a0e1a',
        'on-secondary': '#001f2e',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      // Extra opacity steps used by the POS design (bg-surface-container/85, bg-error/15, ...)
      opacity: {
        15: '0.15',
        85: '0.85',
      },
    },
  },
  plugins: [],
}
