export const CATEGORIES = [
  'Semua Layanan',
  'Kiloan Reguler',
  'Kiloan Kilat / Express',
  'Satuan Premium',
  'Sepatu & Tas',
  'Dry Clean',
]

export const DURATIONS = [
  {
    id: 'reguler',
    label: 'Reguler 2H',
    sub: 'Rp 8.000/kg',
    subClass: 'text-on-surface-variant',
    price: 8000,
    suffix: 'Reguler',
  },
  {
    id: 'kilat',
    label: 'Kilat 24J',
    sub: '+Rp 4.000',
    subClass: 'text-primary',
    price: 12000,
    suffix: 'Kilat 24J',
  },
  {
    id: 'express',
    label: 'Express 6J',
    sub: '+Rp 8.000',
    subClass: 'text-tertiary',
    price: 16000,
    suffix: 'Express 6J',
  },
]

export const SERVICES = [
  {
    id: 'cuci-komplit',
    name: 'Cuci Komplit Kiloan',
    desc: 'Cuci + Pengering + Setrika Uap Rapi',
    icon: 'dry_cleaning',
    iconClass: 'bg-primary-container/40 text-primary',
    badge: { text: 'FAVORIT', className: 'bg-primary/10 text-primary' },
    rateLabel: 'Harga Dasar',
    unitLabel: 'kg',
    unit: 'kg',
    price: 8000,
    priceClass: 'text-primary',
    categories: ['Kiloan Reguler', 'Kiloan Kilat / Express'],
    hasDuration: true,
  },
  {
    id: 'cuci-kering',
    name: 'Cuci Kering Lipat',
    desc: 'Cuci steril suhu tinggi & lipat rapi tanpa setrika',
    icon: 'water_voc',
    iconClass: 'bg-secondary-container/40 text-secondary',
    time: '2 Hari',
    rateLabel: 'Tarif Kiloan',
    unitLabel: 'kg',
    unit: 'kg',
    price: 6000,
    priceClass: 'text-primary',
    categories: ['Kiloan Reguler'],
  },
  {
    id: 'setrika',
    name: 'Setrika Saja (Steam Uap)',
    orderName: 'Setrika Uap Premium',
    desc: 'Pelicin premium & wangi tahan 14 hari',
    icon: 'iron',
    iconClass: 'bg-surface-container-highest text-primary',
    time: '1 Hari',
    rateLabel: 'Tarif Kiloan',
    unitLabel: 'kg',
    unit: 'kg',
    price: 5000,
    priceClass: 'text-primary',
    categories: ['Kiloan Reguler'],
  },
  {
    id: 'sneakers',
    name: 'Sneakers Deep Clean',
    orderName: 'Sepatu Sneakers Deep Clean',
    desc: 'Sole unyellowing, mid & insole conditioning',
    icon: 'steps',
    iconClass: 'bg-tertiary-container/30 text-tertiary',
    badge: { text: 'CARE', className: 'bg-tertiary/10 text-tertiary' },
    rateLabel: 'Tarif Satuan',
    unitLabel: 'psg',
    unit: 'psg',
    price: 35000,
    priceClass: 'text-tertiary',
    categories: ['Sepatu & Tas'],
  },
  {
    id: 'jas',
    name: 'Jas / Blazer Set Dry Clean',
    desc: 'Treatment kimiawi non-air + hanger cover anti-dust',
    icon: 'apparel',
    iconClass: 'bg-primary-container/30 text-primary',
    time: '3 Hari',
    rateLabel: 'Tarif Satuan',
    unitLabel: 'set',
    unit: 'set',
    price: 45000,
    priceClass: 'text-primary',
    categories: ['Dry Clean'],
  },
  {
    id: 'bedcover',
    name: 'Bedcover King Size',
    desc: 'Sanitasi anti-tungau & vacuum sealed packaging',
    icon: 'bed',
    iconClass: 'bg-surface-container-highest text-secondary',
    time: '2 Hari',
    rateLabel: 'Tarif Satuan',
    unitLabel: 'pcs',
    unit: 'pcs',
    price: 30000,
    priceClass: 'text-primary',
    categories: ['Satuan Premium'],
  },
  {
    id: 'karpet',
    name: 'Cuci Karpet Bulu / Tebal',
    orderName: 'Cuci Karpet Bulu Tebal',
    desc: 'Ekstraksi noda dalam & pengering blower 360°',
    icon: 'texture',
    iconClass: 'bg-secondary-container/30 text-secondary',
    time: '4 Hari',
    rateLabel: 'Tarif Meteran',
    unitLabel: 'm²',
    unit: 'm²',
    price: 20000,
    priceClass: 'text-primary',
    categories: ['Satuan Premium'],
  },
  {
    id: 'tas-kulit',
    name: 'Cuci Tas Kulit Luxury',
    desc: 'Leather moisturizer & proteksi jamur mikroskopik',
    icon: 'shopping_bag',
    iconClass: 'bg-tertiary-container/40 text-tertiary',
    badge: { text: 'PREMIUM', className: 'bg-tertiary/10 text-tertiary' },
    rateLabel: 'Tarif Satuan',
    unitLabel: 'pcs',
    unit: 'pcs',
    price: 55000,
    priceClass: 'text-tertiary',
    categories: ['Sepatu & Tas'],
  },
]

// Nota awal sesuai desain: 4,85 kg @ Rp 8.000 + 1 pasang sneakers @ Rp 35.000 = Rp 73.800
export const INITIAL_ITEMS = [
  {
    id: 'cuci-komplit-reguler',
    name: 'Cuci Komplit Kiloan (Reguler)',
    rate: 8000,
    unit: 'kg',
    qty: 4.85,
    step: 0.05,
    note: {
      icon: 'air',
      text: 'Aroma: Ocean Breeze',
      className: 'text-[10px] text-on-surface-variant bg-surface-container/60',
      iconClass: 'text-[13px] text-primary',
    },
  },
  {
    id: 'sneakers',
    name: 'Sepatu Sneakers Deep Clean',
    rate: 35000,
    unit: 'psg',
    qty: 1,
    step: 1,
    note: {
      icon: 'verified',
      text: 'Treatment Khusus Insole',
      className: 'text-[10px] text-tertiary bg-tertiary-container/30',
      iconClass: 'text-[13px]',
    },
  },
]

export const UNIT_WORDS = { kg: 'kg', psg: 'pasang', pcs: 'pcs', set: 'set', 'm²': 'm²' }
export const UNIT_SHORT = { kg: 'Kg', psg: 'Psg', pcs: 'Pcs', set: 'Set', 'm²': 'm²' }

export function formatRp(value) {
  return `Rp ${Math.round(value).toLocaleString('id-ID')}`
}
